"""Run GPTQModel quantize → save (HF GPTQ format for vLLM)."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from luban_sculpt.backends.gptq.config_builder import build_gptq_config, resolve_model_id
from luban_sculpt.calib import CalibRunner
from luban_sculpt.contracts import BackendPlan
from luban_sculpt.log import get_logger

logger = get_logger(__name__)


def is_gptqmodel_available() -> bool:
    try:
        import gptqmodel  # noqa: F401

        return True
    except ImportError:
        return False


def run_gptqmodel_quantize(
    plan: BackendPlan,
    output_dir: Path,
    *,
    dry_run: bool | None = None,
) -> dict[str, Any]:
    """GPTQModel.load → quantize → save；dry-run 时写配置 stub。"""
    output_dir.mkdir(parents=True, exist_ok=True)
    model_id = resolve_model_id(plan)
    quant_config = build_gptq_config(plan)
    opts = plan.intent.backend_options or {}
    gptq_opts = opts.get("gptq") or opts
    calib_runner = CalibRunner(plan)
    batch_size = int(gptq_opts.get("batch_size", calib_runner.batch_size))

    meta: dict[str, Any] = {
        "backend": "gptq",
        "model_id": model_id,
        "quant_config_repr": repr(quant_config),
        "export": "gptq_hf",
    }

    if dry_run is None:
        dry_run = os.environ.get("LUBAN_GPTQMODEL_DRY_RUN", "").lower() in (
            "1",
            "true",
            "yes",
        )

    if dry_run or not is_gptqmodel_available():
        if not dry_run and not is_gptqmodel_available():
            logger.warning("gptqmodel not installed; dry-run. pip install gptqmodel")
        logger.info("gptq dry-run model_id=%s output=%s", model_id, output_dir)
        script = _render_script(plan, output_dir, model_id, batch_size)
        (output_dir / "gptqmodel_quantize.py").write_text(script, encoding="utf-8")
        (output_dir / "gptq_config_stub.json").write_text(
            json.dumps(
                quant_config if isinstance(quant_config, dict) else {"repr": repr(quant_config)},
                indent=2,
            ),
            encoding="utf-8",
        )
        meta["status"] = "dry_run"
        meta["calib_report"] = calib_runner.load().report
        meta["vllm_hint"] = f'LLM("{output_dir}", quantization="gptq")'
        return meta

    from gptqmodel import GPTQModel

    calib_data = calib_runner.load()
    calibration_dataset = calib_data.texts
    logger.info(
        "GPTQModel.load model=%s calib_samples=%d batch=%d",
        model_id,
        len(calibration_dataset),
        batch_size,
    )
    model = GPTQModel.load(model_id, quant_config)
    model.quantize(calibration_dataset, batch_size=batch_size)
    model.save(str(output_dir))

    meta["status"] = "ok"
    meta["calib_report"] = calib_data.report
    meta["calib_samples"] = calib_data.num_samples
    meta["output_dir"] = str(output_dir)
    meta["vllm_hint"] = f'LLM("{output_dir}", quantization="gptq")'
    return meta


def _render_script(
    plan: BackendPlan, output_dir: Path, model_id: str, batch_size: int
) -> str:
    gptq = (plan.intent.backend_options or {}).get("gptq") or plan.intent.backend_options or {}
    bits = gptq.get("bits", 4)
    group_size = gptq.get("group_size", 128)
    return f'''"""Generated by luban-sculpt — pip install gptqmodel datasets"""
from gptqmodel import GPTQConfig, GPTQModel

MODEL_ID = {model_id!r}
SAVE_DIR = {str(output_dir)!r}

calibration_dataset = ["calib stub line 1", "calib stub line 2"]
quant_config = GPTQConfig(bits={bits}, group_size={group_size})

model = GPTQModel.load(MODEL_ID, quant_config)
model.quantize(calibration_dataset, batch_size={batch_size})
model.save(SAVE_DIR)
'''
